#!/usr/bin/env python3
"""Generate testing (crafted.localhost) variants of prod-shaped Server Scripts.

Prod (erp.craftedgoods.ca) DocTypes carry the 'CRAFTED ' prefix; the local app renamed
them (see ../EXPORT_MANIFEST.json doctype_rename). server_scripts/*.py stay prod-shaped;
this writes server_scripts_local/<slug>.py + .json with local DocType names and URLs.

Usage: python3 make_local_variants.py   (then install with install_local_server_scripts.py)
"""
import json, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "server_scripts")
DST = os.path.join(HERE, "server_scripts_local")

# slug -> overrides for the local Server Script record
PORTED = {
    "create_time_sheet_for_employee": {},
    "clock_out_employee_after_shift_is_over": {},
    "alert_shop_on_missed_clock_in": {},
    "alert_missed_schedule_clock_in": {"disabled": 1},
}

RENAME = {
    "CRAFTED Store Schedule": "Store Schedule",
    "CRAFTED Timesheets": "Timesheets",
    "CRAFTED Timesheet Detail": "Timesheets Detail",
    "CRAFTED Employee Info": "Employee Info",
}
LOCAL_BASE = "http://crafted.localhost:8000"
URL_RE = re.compile(r"https://erp\.craftedgoods\.ca/app/crafted-store-schedule/")

def localize(script, slug):
    for a in sorted(RENAME, key=len, reverse=True):
        script = script.replace(a, RENAME[a])
    # local links: /app/store-schedule on the testing site
    script = URL_RE.sub(LOCAL_BASE + "/app/store-schedule/", script)
    script = script.replace("https://erp.craftedgoods.ca/", LOCAL_BASE + "/")
    if slug == "create_time_sheet_for_employee":
        # Timesheets DocType is not part of the local app yet: skip quietly instead of logging on every OUT
        script = script.replace(
            'try:\n    if doc.log_type == "OUT":\n        build_timesheet_row(doc)',
            'try:\n    if doc.log_type == "OUT" and frappe.db.exists("DocType", "Timesheets"):\n        build_timesheet_row(doc)')
        assert 'frappe.db.exists("DocType", "Timesheets")' in script
    assert "CRAFTED " not in script.replace("CRAFTED_", "").replace("Crafted", ""), slug
    return "# LOCAL VARIANT (crafted.localhost) - generated by make_local_variants.py, do not edit by hand\n" + script

def main():
    os.makedirs(DST, exist_ok=True)
    for slug, over in PORTED.items():
        meta = json.load(open(os.path.join(SRC, slug + ".json")))
        s = localize(meta["script"], slug)  # .json script is the canonical copy
        for a, b in RENAME.items():
            if meta.get("reference_doctype") == a:
                meta["reference_doctype"] = b
        meta.update(over)
        meta["script"] = s
        open(os.path.join(DST, slug + ".py"), "w").write(s)
        open(os.path.join(DST, slug + ".json"), "w").write(json.dumps(meta, indent=2, ensure_ascii=False) + "\n")
        print("wrote", slug)

if __name__ == "__main__":
    main()
